#!/bin/sh

builddir="$1"
srcdir="$2"

if test "x$3" = "xdist"; then
  builddir="$MESONPROJECTDIST_ROOT"
fi

version_h_path="${builddir}/git_version.h"
root_version_h_path="${srcdir}/git_version.h"

if test -e "${root_version_h_path}"; then
  # If there is a git_version.h in the project root (as would be generated by meson dist),
  # copy it to the build folder so it's picked up by the following logic
  if ! cmp -s "${version_h_path}" "${root_version_h_path}"; then
    cp "${root_version_h_path}" "${version_h_path}"
  fi
fi

# If no git repo try to read from the existing git_version.h, for building from tarballs
if ! test -d "${srcdir}/.git" -o -f "${srcdir}/.git"; then
  if test -f "${version_h_path}"; then
    while read line; do
      set -- $line
      export $2=$(echo $3 | sed 's/"//g')
    done < "${version_h_path}"
    if test x$BUILD_GIT_VERSION_NUMBER != x -a x$BUILD_GIT_VERSION_STRING != x; then
      exit 0
    else
      echo "invalid git_version.h"
      exit 2
    fi
  else
    echo "git repo not found and no cached git_version.h"
    exit 2
  fi
fi
osx_bundle_sed_path="${builddir}/osx-bundle.sed"

git() {
  command git -C "$srcdir" "$@"
}

# SubStation version scheme (fresh start, no carryover from the old SVN
# revision count):
#   tagged release:    v1.0.0, v1.0.1, v1.1.0, ...
#   N commits after:   v1.0.0-1, v1.0.0-2, ...
#
# The counter is the number of commits since the most recent vX.Y.Z tag.
# The very first tagged release of SubStation (e.g. v1.0.0) is the only one
# without a counter; subsequent commits become v1.0.0-1, v1.0.0-2, etc.
# Any new semver tag resets the counter.
get_latest_semver_tag() {
  git tag --list 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null | sort -V | tail -1
}

# Base version: use the most recent semver tag, or fall back to the project
# version (set in meson.build) for the very first untagged commit.
base_tag=$(get_latest_semver_tag)
if [ -n "$base_tag" ]; then
  installer_version="${base_tag#v}"
else
  # Match the version declared in meson.build. SubStation is a fresh
  # product; the first tagged release becomes v1.0.0 and everything
  # before it is also branded 1.0.0.
  installer_version="1.0.0"
fi

if [ -n "$base_tag" ] && [ "$(git cat-file -t "${base_tag}" 2>/dev/null)" = "commit" ]; then
  # Count commits since the most recent semver tag
  git_revision=$(git rev-list --count "${base_tag}"..HEAD)
else
  # No semver tags yet: use 0 so the first release doesn't get a -0.
  git_revision=0
fi

# Build the human-readable version string. Drop the leading -0 so we never
# produce v1.0.0-0; show only v1.0.0 for the first commit on a fresh line.
if [ "$git_revision" = "0" ]; then
  git_version_str="${installer_version}"
  git_version_short="${installer_version}"
else
  git_version_str="${installer_version}-${git_revision}"
  git_version_short="${installer_version}-${git_revision}"
fi

# Add the branch + short hash to the full version string for diagnostic
# output. The short form (no branch/hash) is what goes into installer names.
if [ "$git_revision" != "0" ]; then
  git_branch="$(git symbolic-ref HEAD 2> /dev/null)" || git_branch="(unnamed branch)"
  git_branch="${git_branch##refs/heads/}"
  git_hash=$(git rev-parse --short HEAD)
  git_version_str="${git_version_str}-${git_branch}-${git_hash}"
fi

tagged_release=0
build_date="$(date "+%Y-%m-%d %H:%M %Z")"

# resource_version is the semver split as comma-separated integers, e.g.
# "1, 0, 0" for the Windows VERSIONINFO resource.
resource_version=$(echo "$installer_version" | sed 's/\./, /g')

new_version_h="\
#define BUILD_GIT_VERSION_NUMBER ${git_revision}
#define BUILD_GIT_VERSION_STRING \"${git_version_str}\"
#define BUILD_GIT_VERSION_SHORT \"${git_version_short}\"
#define TAGGED_RELEASE ${tagged_release}
#define INSTALLER_VERSION \"${installer_version}\"
#define RESOURCE_BASE_VERSION ${resource_version}"

osx_bundle_sed="\
s/@PLIST_VERSION@/${git_version_str}/g
s/@PLIST_BUILD_DATE@/${build_date}/g
/ *@LOCALIZATIONS@/ {
  r languages
  d
}"

# Write it only if it's changed to avoid spurious rebuilds
# This bizarre comparison method is due to that newlines in shell variables are very exciting
case "$(cat ${version_h_path} 2> /dev/null)"
in
  "${new_version_h}");;
  *)
    echo "${new_version_h}" > "${version_h_path}"
    echo "${osx_bundle_sed}" > "${osx_bundle_sed_path}"
    ;;
esac
