#!/bin/sh

builddir="$1"
srcdir="$2"

if test "x$3" = "xdist"; then
  builddir="$MESON_PROJECT_DIST_ROOT"
fi

version_h_path="${builddir}/git_version.h"
root_version_h_path="${srcdir}/git_version.h"

if test -e "${root_version_h_path}"; then
  # If there is a git_version.h in the project root (as would be generated by meson dist),
  # copy it to the build folder so it's picked up by the following logic

  if ! cmp -s "${version_h_path}" "${root_version_h_path}"; then
    cp "${root_version_h_path}" "${version_h_path}"
  fi
fi

# If no git repo try to read from the existing git_version.h, for building from tarballs
if ! test -d "${srcdir}/.git" -o -f "${srcdir}/.git"; then
  if test -f "${version_h_path}"; then
    while read line; do
      set -- $line
      export $2=$(echo $3 | sed 's/"//g')
    done < "${version_h_path}"
    if test x$BUILD_GIT_VERSION_NUMBER != x -a x$BUILD_GIT_VERSION_STRING != x; then
      exit 0
    else
      echo "invalid git_version.h"
      exit 2
    fi
  else
    echo "git repo not found and no cached git_version.h"
    exit 2
  fi
fi
osx_bundle_sed_path="${builddir}/osx-bundle.sed"

last_svn_revision=6962
last_svn_hash="16cd907fe7482cb54a7374cd28b8501f138116be"

git() {
  command git -C "$srcdir" "$@"
}

# Compute the build counter (N) and the base installer version.
#
# Semver scheme: Aegisub-vX.Y.Z-N-{x64,arm64}.exe
#   - v3.5.0: a clean tagged release; counter omitted.
#   - v3.5.0-1, v3.5.0-2, ...: commits on top of 3.5.0 within the 3.5.x line.
#   - v3.5.1: minor or patch bump; the counter resets (no v3.5.1-0).
#   - v3.6.0: next feature release; counter resets.
#
# The counter is the number of commits since the most recent vX.Y.Z tag.
# Any new semver tag (whether the same minor line or a fresh one) resets
# the counter to 0; we then drop the -0 suffix so the very next commit
# on top of a fresh tag is "v3.5.0" instead of "v3.5.0-0".
#
# If no semver tag exists yet at all, fall back to the original SVN
# baseline so the very first release still has a real-looking number.
get_latest_semver_tag() {
  git tag --list 'v[0-9]*.[0-9]*.[0-9]*' 2>/dev/null | sort -V | tail -1
}

if [ "$(git cat-file -t $last_svn_hash 2> /dev/null)" = "commit" ]; then
  base_tag=$(get_latest_semver_tag)
  if [ -n "$base_tag" ] && [ "$(git cat-file -t "${base_tag#v}" 2> /dev/null)" = "commit" ]; then
    # Count commits since the most recent semver tag
    git_revision=$(git rev-list --count "${base_tag}"..HEAD)
  else
    # No semver tags yet; use the original SVN baseline
    git_revision=$(expr $last_svn_revision + $(git rev-list --count $last_svn_hash..HEAD))
  fi
else
  git_revision=0
fi
git_version_str=$(git describe --tags --exact-match 2> /dev/null)
installer_version='0.0.0'
resource_version='0, 0, 0'
git_version_short='0.0.0'
if test x$git_version_str != x; then
  git_version_str="${git_version_str##v}"
  tagged_release=1
  if [ $(echo $git_version_str | grep '^[0-9]\.[0-9]\.[0-9]$') ]; then
    installer_version=$git_version_str
    resource_version=$(echo $git_version_str | sed 's/\./, /g')
    git_version_short=$git_version_str
  fi
else
  git_branch="$(git symbolic-ref HEAD 2> /dev/null)" || git_branch="(unnamed branch)"
  git_branch="${git_branch##refs/heads/}"
  git_hash=$(git rev-parse --short HEAD)

  # Pick the most recent semver tag to use as the base version. If no
  # semver tag exists yet, fall back to the project version so the
  # installer name is always a real semver triple (e.g. 3.5.0) instead
  # of the meaningless 0.0.0 placeholder.
  base_tag=$(get_latest_semver_tag)
  if [ -n "$base_tag" ]; then
    installer_version="${base_tag#v}"
  else
    installer_version='3.5.0'
  fi
  resource_version=$(echo $installer_version | sed 's/\./, /g')

  # Build the human-readable version string. Drop the leading -0 so we
  # never produce v3.5.0-0; show only v3.5.0 for the first commit on a
  # fresh minor line.
  if [ "$git_revision" = "0" ]; then
    git_version_str="${installer_version}"
    git_version_short="${installer_version}"
  else
    git_version_str="${installer_version}-${git_revision}"
    git_version_short="${installer_version}-${git_revision}"
  fi
  git_version_str="${git_version_str}-${git_branch}-${git_hash}"
  tagged_release=0
fi

build_date="$(date "+%Y-%m-%d %H:%M %Z")"

new_version_h="\
#define BUILD_GIT_VERSION_NUMBER ${git_revision}
#define BUILD_GIT_VERSION_STRING \"${git_version_str}\"
#define BUILD_GIT_VERSION_SHORT \"${git_version_short}\"
#define TAGGED_RELEASE ${tagged_release}
#define INSTALLER_VERSION \"${installer_version}\"
#define RESOURCE_BASE_VERSION ${resource_version}"

osx_bundle_sed="\
s/@PLIST_VERSION@/${git_version_str}/g
s/@PLIST_BUILD_DATE@/${build_date}/g
/ *@LOCALIZATIONS@/ {
  r languages
  d
}"

# Write it only if it's changed to avoid spurious rebuilds
# This bizarre comparison method is due to that newlines in shell variables are very exciting
case "$(cat ${version_h_path} 2> /dev/null)"
in
  "${new_version_h}");;
  *)
    echo "${new_version_h}" > "${version_h_path}"
    echo "${osx_bundle_sed}" > "${osx_bundle_sed_path}"
    ;;
esac
